Primjeri/Web/Firma.Mvc/Models/Artikl.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace Firma.Mvc.Models
{
  public partial class Artikl
  {
    public Artikl()
    {
      Stavka = new HashSet<Stavka>();
    }

    [Required(ErrorMessage = "Potrebno je unijeti šifru artikla")]
    [Display(Name = "Šifra artikla")]
    public int SifArtikla { get; set; }

    [Required(ErrorMessage = "Potrebno je unijeti naziv artikla")]
    [Display(Name = "Naziv artikla")]
    [MaxLength(255, ErrorMessage = "Naziv ne smije biti dulji od 255 znakova")]
    public string NazArtikla { get; set; }

    [Required(ErrorMessage = "Potrebno je unijeti jedinicu mjere")]
    [Display(Name = "Jedinica mjere")]
    [MaxLength(5, ErrorMessage = "Maksimalna duljina za jedinicu mjere je 5")]
    public string JedMjere { get; set; }

    [Required(ErrorMessage = "Potrebno je unijeti cijenu artikla")]
    [Display(Name = "Cijena artikla")]
    [Range(0.01, 100000.0, ErrorMessage = "Cijena mora biti pozitivni broj manji od 100 000")]
    public decimal CijArtikla { get; set; }

    [Display(Name = "Usluga")]
    public bool ZastUsluga { get; set; }

    [Display(Name = "Slika artikla")]
    public byte[] SlikaArtikla { get; set; }

    [Display(Name = "Opis artikla")]
    public string TekstArtikla { get; set; }

    public int? SlikaChecksum { get; set; }

    public ICollection<Stavka> Stavka { get; set; }
  }
}

Primjeri/Web/Firma.Mvc/ViewModels/ArtiklViewModel.cs
namespace Firma.Mvc.ViewModels
{
  public class ArtiklViewModel
  {
    public int SifraArtikla { get; set; }
    public string NazivArtikla { get; set; }
    public string JedinicaMjere { get; set; }
    public decimal CijenaArtikla { get; set; }
    public bool Usluga { get; set; }
    public string TekstArtikla { get; set; }
    public bool ImaSliku { get; set; }
    public int? ImageHash { get; set; }
  }
}

Primjeri/Web/Firma.Mvc/Controllers/ArtiklController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using System.IO;
using Firma.Mvc.Extensions;
using Firma.Mvc.Models;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Options;
using Microsoft.EntityFrameworkCore;
using Firma.Mvc.ViewModels;
using System.Threading.Tasks;

namespace Firma.Mvc.Controllers
{
  public class ArtiklController : Controller
  {
    private readonly FirmaContext ctx;
    private readonly AppSettings appData;

    public ArtiklController(FirmaContext ctx, IOptionsSnapshot<AppSettings> options)
    {
      this.ctx = ctx;
      appData = options.Value;
    }

    public IActionResult Index(int page = 1, int sort = 1, bool ascending = true)
    {
      int pagesize = appData.PageSize;
      var query = ctx.Artikl.AsNoTracking();
      int count = query.Count();

      var pagingInfo = new PagingInfo
      {
        CurrentPage = page,
        Sort = sort,
        Ascending = ascending,
        ItemsPerPage = pagesize,
        TotalItems = count
      };
      if (page < 1)
      {
        page = 1;
      }
      else if (page > pagingInfo.TotalPages)
      {
        return RedirectToAction(nameof(Index), new { page = pagingInfo.TotalPages, sort, ascending });
      }

      System.Linq.Expressions.Expression<Func<Artikl, object>> orderSelector = null;
      switch (sort)
      {
        //po slici se ne može sortirati, pa zato nema case 1:
        case 2:
          orderSelector = a => a.SifArtikla;
          break;
        case 3:
          orderSelector = a => a.NazArtikla;
          break;
        case 4:
          orderSelector = a => a.JedMjere;
          break;
        case 5:
          orderSelector = a => a.CijArtikla;
          break;
        case 6:
          orderSelector = a => a.ZastUsluga;
          break;
      }
      if (orderSelector != null)
      {
        query = ascending ?
               query.OrderBy(orderSelector) :
               query.OrderByDescending(orderSelector);
      }

      var artikli = query
                    .Select(a => new ArtiklViewModel
                    {
                      SifraArtikla = a.SifArtikla,
                      NazivArtikla = a.NazArtikla,
                      JedinicaMjere = a.JedMjere,
                      CijenaArtikla = a.CijArtikla,
                      Usluga = a.ZastUsluga,
                      TekstArtikla = a.TekstArtikla,
                      ImaSliku = a.SlikaArtikla != null,
                      ImageHash = a.SlikaChecksum
                    })
                    .Skip((page - 1) * pagesize)
                    .Take(pagesize)
                    .ToList();
      var model = new ArtikliViewModel
      {
        Artikli = artikli,
        PagingInfo = pagingInfo
      };

      return View(model);
    }

    [HttpGet]
    public IActionResult Create()
    {
      return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(Artikl artikl, IFormFile slika)
    {
      if (artikl.CijArtikla <= 0)
      {
        ModelState.AddModelError(nameof(Artikl.CijArtikla), "Cijena mora biti pozitivni broj");
      }
      else
      {
        //provjeri jedinstvenost šifre artikla
        bool exists = await ctx.Artikl.AnyAsync(a => a.SifArtikla == artikl.SifArtikla);
        if (exists)
        {
          ModelState.AddModelError(nameof(Artikl.SifArtikla), "Artikl s navedenom šifrom već postoji");
        }
      }
      if (ModelState.IsValid)
      {
        try
        {
          if (slika != null && slika.Length > 0)
          {
            using (MemoryStream stream = new MemoryStream())
            {
              await slika.CopyToAsync(stream);
              artikl.SlikaArtikla = stream.ToArray();
            }
          }
          ctx.Add(artikl);
          await ctx.SaveChangesAsync();

          TempData[Constants.Message] = $"Artikl  {artikl.SifArtikla} - {artikl.NazArtikla} dodan";
          TempData[Constants.ErrorOccurred] = false;
          return RedirectToAction(nameof(Index));

        }
        catch (Exception exc)
        {
          ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
          return View(artikl);
        }
      }
      else
      {
        return View(artikl);
      }
    }

    public FileContentResult GetImage(int id)
    {
      byte[] image = ctx.Artikl
                        .Where(a => a.SifArtikla == id)
                        .Select(a => a.SlikaArtikla)
                        .SingleOrDefault();
      if (image != null)
        return File(image, "image/jpeg");
      else
        return null;
    }

    [HttpGet]
    public IActionResult Edit(int id)
    {
      var artikl = ctx.Artikl.Find(id);
      if (artikl != null)
      {
        return PartialView(artikl);
      }
      else
      {
        return NotFound($"Neispravna šifra artikla: {id}");
      }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Edit(Artikl artikl, IFormFile slika, bool obrisiSliku)
    {
      if (artikl == null)
      {
        return NotFound("Nema poslanih podataka");
      }
      Artikl dbArtikl = ctx.Artikl.FirstOrDefault(a => a.SifArtikla == artikl.SifArtikla);
      if (dbArtikl == null)
      {
        return NotFound($"Neispravna šifra artikla: {artikl.SifArtikla}");
      }

      if (artikl.CijArtikla <= 0)
      {
        ModelState.AddModelError(nameof(Artikl.CijArtikla), "Cijena mora biti pozitivni broj");
      }

      if (ModelState.IsValid)
      {
        try
        {
          //ne možemo ići na varijantu ctx.Update(artikl), jer nismo prenosili sliku, pa bi bila obrisana
          dbArtikl.JedMjere = artikl.JedMjere;
          dbArtikl.NazArtikla = artikl.NazArtikla;
          dbArtikl.ZastUsluga = artikl.ZastUsluga;
          dbArtikl.TekstArtikla = artikl.TekstArtikla;
          dbArtikl.CijArtikla = artikl.CijArtikla;

          if (slika != null && slika.Length > 0)
          {
            using (MemoryStream stream = new MemoryStream())
            {
              slika.CopyTo(stream);
              dbArtikl.SlikaArtikla = stream.ToArray();
            }
          }
          else if (obrisiSliku)
          {
            dbArtikl.SlikaArtikla = null;
          }

          ctx.SaveChanges();
          return StatusCode(302, Url.Action(nameof(Row), new { id = dbArtikl.SifArtikla }));
        }
        catch (Exception exc)
        {
          ModelState.AddModelError(string.Empty, exc.CompleteExceptionMessage());
          return PartialView(artikl);
        }
      }
      else
      {
        return PartialView(artikl);
      }
    }

    public PartialViewResult Row(int id)
    {
      var artikl = ctx.Artikl
                       .AsNoTracking()
                       .Where(a => a.SifArtikla == id)
                       .Select(a => new ArtiklViewModel
                       {
                         SifraArtikla = a.SifArtikla,
                         NazivArtikla = a.NazArtikla,
                         JedinicaMjere = a.JedMjere,
                         CijenaArtikla = a.CijArtikla,
                         Usluga = a.ZastUsluga,
                         TekstArtikla = a.TekstArtikla,
                         ImaSliku = a.SlikaArtikla != null,
                         ImageHash = a.SlikaChecksum
                       })
                       .SingleOrDefault();
      if (artikl != null)
      {
        return PartialView(artikl);
      }
      else
      {
        //vratiti prazan sadržaj?
        return PartialView("ErrorMessageRow", $"Neispravna šifra artikla: {id}");
      }
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public IActionResult Delete(int id)
    {
      var artikl = ctx.Artikl.Find(id);
      if (artikl != null)
      {
        try
        {
          string naziv = artikl.NazArtikla;
          ctx.Remove(artikl);
          ctx.SaveChanges();
          var result = new
          {
            message = $"Artikl {naziv} sa šifrom {id} uspješno obrisan.",
            successful = true
          };
          return Json(result);
        }
        catch (Exception exc)
        {
          var result = new
          {
            message = "Pogreška prilikom brisanja artikla: " + exc.CompleteExceptionMessage(),
            successful = false
          };
          return Json(result);
        }
      }
      else
      {
        return NotFound($"Artikl sa šifrom {id} ne postoji");
      }
    }
  }
}

Primjeri/Web/Firma.Mvc/Controllers/AutoComplete/ArtiklController.cs
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Firma.Mvc.Models;
using Microsoft.Extensions.Options;

// For more information on enabling Web API for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860

namespace Firma.Mvc.Controllers.AutoComplete
{
    [Route("autocomplete/[controller]")]
    public class ArtiklController : Controller
    {
        private readonly FirmaContext ctx;
        private readonly AppSettings appData;

        public ArtiklController(FirmaContext ctx, IOptionsSnapshot<AppSettings> options)
        {
            this.ctx = ctx;
            appData = options.Value;
        }
        
        [HttpGet]      
        public IEnumerable<Artikl> Get(string term)
        {
            var query = ctx.Artikl
                           .Where(a => a.NazArtikla.Contains(term))
                           .OrderBy(a => a.NazArtikla)                           
                           .Select(a => new Artikl
                           {
                               Id = a.SifArtikla,
                               Label = a.NazArtikla,
                               Cijena = a.CijArtikla
                           });
            var list = query.Take(appData.AutoCompleteCount).ToList();
            return list;
        }       
    }
}

Primjeri/Web/Firma.Mvc/Views/Artikl/Create.cshtml
@model Artikl

@{
  ViewBag.Title = "Novi artikl";
}

<h2>Unos novog artikla</h2>

<div class="container">
  <form asp-action="Create" method="post" enctype="multipart/form-data">
    <div asp-validation-summary="All" class="form-group row"></div>

    <div class="form-group row">
      <label asp-for="SifArtikla" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-5">
        <input asp-for="SifArtikla" class="form-control" />
      </div>
      <span asp-validation-for="SifArtikla" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <label asp-for="NazArtikla" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-5">
        <input asp-for="NazArtikla" class="form-control" />
      </div>
      <span asp-validation-for="NazArtikla" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <label asp-for="JedMjere" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-5">
        <input asp-for="JedMjere" class="form-control" />
      </div>
      <span asp-validation-for="JedMjere" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <label asp-for="CijArtikla" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-5">
        <input asp-for="CijArtikla" class="form-control" />
      </div>
      <span asp-validation-for="CijArtikla" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <label asp-for="ZastUsluga" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-1 text-left">
        <input asp-for="ZastUsluga" class="form-control input-sm" />
      </div>
      <span asp-validation-for="ZastUsluga" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <label asp-for="TekstArtikla" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-5">
        <input asp-for="TekstArtikla" class="form-control" />
      </div>
      <span asp-validation-for="TekstArtikla" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <label asp-for="SlikaArtikla" class="col-sm-2 col-form-label"></label>
      <div class="col-sm-5">
        <input type="file" name="slika" />
      </div>
      <span asp-validation-for="SlikaArtikla" class="col-sm-5 text-danger"></span>
    </div>

    <div class="form-group row">
      <div class="col-sm-2"></div>
      <div class="col-sm-5">
        <button class="btn btn-primary" type="submit">Dodaj</button>
        <a asp-action="Index" class="btn btn-secondary">Odustani</a>
      </div>
    </div>
  </form>
</div>

Primjeri/Web/Firma.Mvc/Views/Artikl/Edit.cshtml
@model Artikl

<tr>
    <td colspan="2">
        @Model.SifArtikla
        <input type="hidden" asp-for="SifArtikla" data-save="" />
    </td>
    <td>
        <input asp-for="NazArtikla" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="JedMjere" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="CijArtikla" class="form-control" data-save="" />
    </td>
    <td>
        <input asp-for="ZastUsluga" class="checkbox" data-save="" />
    </td>
    <td>
        <input asp-for="TekstArtikla" class="form-control" data-save="" />
    </td>   
    <td>
        <button type="submit" class="btn btn-sm btn-primary save" title="Spremi"><i class="fas fa-save"></i></button>
    </td>
    <td>
        <button class="btn btn-sm cancel" title="Odustani"><i class="fas fa-undo-alt"></i></button>
    </td>
</tr>
<tr>
  <td colspan="3">
    <input type="checkbox" name="obrisisliku" data-save="" />
    <span class="text-info">Obriši sliku ?</span>
  </td>
  <td colspan="2">
    <div asp-validation-summary="All"></div>
  </td>
  <td colspan="4">
    Zamijeni sliku s nekom drugom <input type="file" name="slika" data-save="" />
  </td>
</tr>

Primjeri/Web/Firma.Mvc/Views/Artikl/ErrorMessageRow.cshtml
@model string

<tr>
  <td colspan="6">
    <span class="validation-summary-errors">@Model</span>
  </td>
</tr>

Primjeri/Web/Firma.Mvc/Views/Artikl/Index.cshtml
@model ArtikliViewModel

@{
    ViewBag.Title = "Artikli";
}

<h2>Popis artikala</h2>


<a asp-action="Create">Unos novog artikla</a>

<pager page-info="@Model.PagingInfo" page-action="Index" page-title="Unesite željenu stranicu"
       class="float-right">
</pager>

<table class="table table-striped">
    <thead>
        <tr>
            @{
                string[] nazivi = { "", "Šifra", "Naziv", "Jedinica mjere", "Cijena", "Usluga", "Opis" };
                bool[] sortable = { false, true, true, true, true, true, false };
                for (int i = 1; i <= nazivi.Length; i++)
                {
                    <th>
                        @if (sortable[i - 1])
                        {
                            <a asp-route-sort="@i" asp-route-page="@Model.PagingInfo.CurrentPage" asp-route-ascending="@(Model.PagingInfo.Sort == i ? !Model.PagingInfo.Ascending : true)">
                                @nazivi[i - 1]
                            </a>
                        }
                        else
                        {
                            @nazivi[i - 1]
                        }
                    </th>
                }
            }
            <th></th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var artikl in Model.Artikli)
        {
          <partial name="Row" model="artikl" />
        }
    </tbody>
</table>

@section scripts{
    <script type="text/javascript">
        $(function () {
            SetEditAjax(".editajax", '@Url.Action("Edit")', 'sifartikla');
            SetDeleteAjax(".deleteajax", '@Url.Action("Delete")', 'sifartikla');
        });
    </script>
}

Primjeri/Web/Firma.Mvc/Views/Artikl/Row.cshtml
@model ArtiklViewModel

<tr>
  <td class="text-left">
    @if (Model.ImaSliku)
    {
      <img src="@Url.Action("GetImage", "Artikl", new { id = @Model.SifraArtikla, hash=Model.ImageHash })"
           class="malaslika" />
    }
  </td>
  <td class="text-left">@Model.SifraArtikla</td>
  <td class="text-left">@Model.NazivArtikla</td>
  <td class="text-left">@Model.JedinicaMjere</td>
  <td class="text-right text-nowrap">@Model.CijenaArtikla.ToString("C2")</td>
  <td class="text-left"><input type="checkbox" @(Model.Usluga ? "checked" : "") disabled />  </td>
  <td class="text-left">@Model.TekstArtikla</td>
  <td>
    <a data-sifartikla="@Model.SifraArtikla" class="btn btn-warning btn-sm editajax" title="Ažuriraj"><i class="fas fa-edit"></i></a>
  </td>
  <td>
      <form asp-action="Delete" method="post">
          @*Neće se koristiti direktni submit, ali treba zbog anti forgery tokena*@
          <input type="hidden" name="id" value="@Model.SifraArtikla" />
          <button data-sifartikla="@Model.SifraArtikla" class="btn btn-sm btn-danger deleteajax" title="Obriši"><i class="fas fa-trash-alt"></i></button>          
      </form>

  </td>
</tr>